### PR TITLE
fix: open connection count

### LINKED ISSUE #520: Pool fails to manage number of open connection?
I've got many context deadline exceeded error from Pool.GetContext.

I suspect it fails to manage number of open connection.
It acquires from p.ch here
https://github.com/gomodule/redigo/blob/6f8b8987f003d0b10dd72673c477b054c9189d2c/redis/pool.go#L385
but should we release it back to p.ch here?
https://github.com/gomodule/redigo/blob/6f8b8987f003d0b10dd72673c477b054c9189d2c/redis/pool.go#L390

otherwise available items in p.ch would decrease and eventually couldn't get new one?

### PR DESCRIPTION
**Pull request by rhnvrm**
This commit releases back the connection in the special
case, so that correct count is always maintained.

Closes #520

### CODE REVIEW

File: redis/pool_test.go [hunk 1]
```diff
@@ -825,6 +825,30 @@ func TestWaitPoolGetContext(t *testing.T) {
...
+func TestWaitPoolGetContextIssue520(t *testing.T) {
+	d := poolDialer{t: t}
+	p := &redis.Pool{
+		MaxIdle:   1,
+		MaxActive: 1,
+		Dial:      d.dial,
+		Wait:      true,
+	}
+	defer p.Close()
+	ctx1, _ := context.WithTimeout(context.Background(), 1*time.Nanosecond)
```
Comment (stevenh) [inline redis/pool_test.go:837]: This leaks a cancel see:
https://travis-ci.org/github/gomodule/redigo/builds/736087424

**Review by stevenh — CHANGES_REQUESTED** [review]
Thanks for the first time PR, couple of little issues with the test to fix go vet.

**Comment by rhnvrm** [comment]
@stevenh sorry for the delay, have pushed the context cancellation change to resolve the `go vet` issue in the test.

**Comment by stevenh** [comment]
Thanks @rhnvrm 👍
