### PR TITLE
Fix Pool.Get to simple code

### LINKED ISSUE #477: Pool.Get code can be simple
The pull request #478 makes the code simple.

### PR DESCRIPTION
**Pull request by 178inaba**
Fixes #477.

### CODE REVIEW

File: redis/pool.go [hunk 1]
```diff
@@ -185,11 +185,8 @@ func NewPool(newFn func() (Conn, error), maxIdle int) *Pool {
 // getting an underlying connection, then the connection Err, Do, Send, Flush
 // and Receive methods return that error.
 func (p *Pool) Get() Conn {
-	pc, err := p.get(nil)
-	if err != nil {
-		return errorConn{err}
-	}
-	return &activeConn{p: p, pc: pc}
+	c, _ := p.GetContext(context.Background())
```
Comment (stevenh) [inline redis/pool.go:188]: Your discarding the error here, which isn't safe

File: redis/pool.go [hunk 2]
```diff
@@ -315,14 +312,10 @@ func (p *Pool) get(ctx context.Context) (*poolConn, error) {
...
-			<-p.ch
-		} else {
-			select {
-			case <-p.ch:
-			case <-ctx.Done():
-				return nil, ctx.Err()
-			}
+		select {
+		case <-p.ch:
+		case <-ctx.Done():
```
Comment (stevenh) [inline redis/pool.go:317]: This will cause a panic if ctx is nil e.g.
https://play.golang.org/p/F4NjaHeF4bi

File: redis/pool.go (hunk 1 above)
Comment (178inaba) [reply redis/pool.go:188]: Like `Get`, `GetContext` returns `errorConn` in case of an error, so I think it's okay.

https://github.com/gomodule/redigo/blob/129455dc28ae7cb56466318ec259422d14851207/redis/pool.go#L203-L209

File: redis/pool.go (hunk 2 above)
Comment (178inaba) [reply redis/pool.go]: Thank you!
I reverted!

File: redis/pool.go (hunk 1 above)
Comment (stevenh) [reply redis/pool.go:188]: We should add a comment to clarify that as its not immediately clear.

Comment (178inaba) [reply redis/pool.go:189]: Added a comment!

**Comment by 178inaba** [comment]
@stevenh I have integrated Pool.get into Pool.GetContext.
I think you can follow because the following godoc comments are described in GetContext.
> The provided Context must be non-nil. If the context expires before the connection is complete, an error is returned. Any expiration on the context will not affect the returned connection.

**Comment by stevenh** [comment]
> @stevenh I have integrated Pool.get into Pool.GetContext.
> I think you can follow because the following godoc comments are described in GetContext.
> 
> > The provided Context must be non-nil. If the context expires before the connection is complete, an error is returned. Any expiration on the context will not affect the returned connection.

Now you have eliminated `get(...)` then I would agree
